services:
  db:
    image: postgres:15-alpine
    container_name: postgres-db-iofmt
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: iofmtadm
      POSTGRES_PASSWORD: Adm!1234
    ports:
      - "5432:5432"
    networks:
      - local

networks:
  local: