on: [push]
name: Deploy Azure

permissions:
      id-token: write
      contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    # checkout the repo
    - uses: actions/checkout@main
    - name: 'Checkout GitHub Action' 
      run: |
        echo ${{ secrets.ENV }} | base64 --decode > .env
    
    - name: 'Sign in via Azure CLI'
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    
    - uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.REGISTRY_URL }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - run: |
        docker build . -t ${{ secrets.REGISTRY_URL }}/${{ secrets.WEBAPI2 }}:${{ github.sha }}
        docker push ${{ secrets.REGISTRY_URL }}/${{ secrets.WEBAPI2 }}:${{ github.sha }}     
      
    - uses: azure/webapps-deploy@v2
      with:
        app-name: '${{ secrets.WEBAPI2 }}'
        images: '${{ secrets.REGISTRY_URL }}/${{ secrets.WEBAPI2 }}:${{ github.sha }}'
    
    - name: Azure logout
      run: |
        az logout